# Generated by Django 5.1.5 on 2025-05-28 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributing_factor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=50)),
                ('contact', models.PositiveBigIntegerField(unique=True)),
                ('Designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='IMS.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Department_poc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poccs', to='IMS.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emppoc', to='IMS.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.department')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_ticket',
            fields=[
                ('Incidentid', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Location', models.CharField(max_length=200)),
                ('Discription', models.CharField(max_length=500, null=True)),
                ('Assign_poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignpoc', to='IMS.department_poc')),
                ('Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.employee')),
                ('contributingfactor', models.ManyToManyField(db_table='incident_factor', to='IMS.contributing_factor')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.department')),
                ('Incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.incident_type')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('Role', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='IMS.role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stack_holder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
