# Generated by Django 5.1.5 on 2025-05-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Role',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='IMS.role'),
        ),
    ]
