# Generated by Django 5.1.5 on 2025-05-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LikehoodRecurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.recurrence')),
                ('RiskLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.risk')),
                ('PotentialSeverity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.severity')),
            ],
        ),
    ]
