# Generated by Django 5.1.5 on 2025-05-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_recurrence_risk_severity_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Riskassessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.riskassessment'),
        ),
    ]
