# Generated by Django 5.1.5 on 2025-05-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0006_incident_ticket_riskassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.evidence'),
        ),
    ]
