# Generated by Django 5.1.5 on 2025-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_evidence_incident_ticket_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Individualsinvolved',
            field=models.ManyToManyField(db_table='Individuals', null=True, related_name='Ticketindividuals', to='IMS.employee'),
        ),
    ]
