# Generated by Django 5.1.5 on 2025-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0008_incident_ticket_individualsinvolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Witnesses',
            field=models.ManyToManyField(db_table='Witnesstable', null=True, related_name='TicketWitnesses', to='IMS.employee'),
        ),
    ]
