# Generated by Django 5.1.5 on 2025-05-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0009_incident_ticket_witnesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Stutus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Statusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.status')),
                ('incidentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.incident_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Status',
            field=models.ManyToManyField(null=True, related_name='TicketStatus', through='IMS.StatusTime', to='IMS.status'),
        ),
    ]
