# Generated by Django 5.1.5 on 2025-05-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0010_status_statustime_incident_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActionTaken', models.CharField(max_length=1000, null=True)),
                ('DateCompleted', models.DateTimeField()),
                ('ReponsiblePerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.employee')),
                ('incidentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.incident_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Followupactions',
            field=models.ManyToManyField(null=True, related_name='TicketFollowup', through='IMS.FollowupAction', to='IMS.employee'),
        ),
        migrations.CreateModel(
            name='ImmediateAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActionDescription', models.CharField(max_length=2000, null=True)),
                ('Employeeid', models.ManyToManyField(db_table='ImmediateActionEmployees', to='IMS.employee')),
                ('incidentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.incident_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Immediateactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TicketImmediateActions', to='IMS.immediateaction'),
        ),
        migrations.CreateModel(
            name='ImprovementRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=700, null=True)),
                ('ResponsiblePerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.employee')),
                ('incidentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.incident_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Improvementrecommendation',
            field=models.ManyToManyField(null=True, related_name='TicketImprovement', through='IMS.ImprovementRecommendation', to='IMS.employee'),
        ),
    ]
