# Generated by Django 5.1.5 on 2025-05-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0011_followupaction_incident_ticket_followupactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Discription',
        ),
    ]
