# Generated by Django 5.1.5 on 2025-05-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0012_remove_incident_ticket_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupaction',
            old_name='ReponsiblePerson',
            new_name='ResponsiblePerson',
        ),
    ]
