# Generated by Django 5.1.5 on 2025-06-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0013_rename_reponsibleperson_followupaction_responsibleperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Immediateactions',
        ),
    ]
