# Generated by Django 5.1.5 on 2025-06-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0015_alter_immediateaction_incidentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Evidence',
        ),
        migrations.AddField(
            model_name='evidence',
            name='incidentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvidenceIncidentID', to='IMS.incident_ticket'),
        ),
    ]
