# Generated by Django 5.1.5 on 2025-06-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0016_remove_incident_ticket_evidence_evidence_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='incidentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvidenceIncident', to='IMS.incident_ticket'),
        ),
    ]
