# Generated by Django 5.1.5 on 2025-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0017_alter_evidence_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_ticket',
            name='Status',
            field=models.ManyToManyField(default=1, null=True, related_name='TicketStatus', through='IMS.StatusTime', to='IMS.status'),
        ),
    ]
