# Generated by Django 5.1.5 on 2025-06-05 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0019_alter_incident_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustime',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
