# Generated by Django 5.1.5 on 2025-06-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0020_alter_statustime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementrecommendation',
            name='ResponsiblePerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='IMS.employee'),
        ),
    ]
