# Generated by Django 5.1.5 on 2025-06-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0021_alter_improvementrecommendation_responsibleperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Role',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='IMS.role'),
        ),
    ]
