# Generated by Django 5.1.5 on 2025-06-16 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0022_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Riskassessment',
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Recurrence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recurrencess', to='IMS.recurrence'),
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='Risk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Riskss', to='IMS.risk'),
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='SeverityLevel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SeverityLevels', to='IMS.severity'),
        ),
    ]
