# Generated by Django 5.1.5 on 2025-06-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0023_remove_incident_ticket_riskassessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvementrecommendation',
            old_name='ResponsiblePerson',
            new_name='employee_id',
        ),
    ]
