# Generated by Django 5.1.5 on 2025-06-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0024_rename_responsibleperson_improvementrecommendation_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvementrecommendation',
            old_name='incidentid',
            new_name='Incidentid',
        ),
    ]
