# Generated by Django 5.1.5 on 2025-06-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0025_rename_incidentid_improvementrecommendation_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementrecommendation',
            name='Incidentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TikectRecommendation', to='IMS.incident_ticket'),
        ),
    ]
