# Generated by Django 5.1.5 on 2025-06-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0026_alter_improvementrecommendation_incidentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_ticket',
            name='Improvementrecommendation',
        ),
    ]
