# Generated by Django 5.1.5 on 2025-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0032_remove_incident_ticket_improvementrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='Improvementrecommendation',
            field=models.ManyToManyField(null=True, related_name='TikectRecommendations', through='IMS.ImprovementRecommendation', to='IMS.employee'),
        ),
    ]
