# Generated by Django 5.1.5 on 2025-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0034_alter_incident_ticket_improvementrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
    ]
