# Generated by Django 5.1.5 on 2025-06-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0035_delete_riskassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupaction',
            name='incidentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followup', to='IMS.incident_ticket'),
        ),
    ]
