# Generated by Django 5.1.5 on 2025-06-18 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0036_alter_followupaction_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustime',
            name='incidentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statuss', to='IMS.incident_ticket'),
        ),
    ]
